version: "3.9"

node-template: &node-template
  build: .
  cpus: 2
  mem-limit: 2048m
  volumes:
    - cluster-shared:/shared
  networks:
    - cluster-net


services:
  master:
    <<: *node-template
    hostname: master
  
  node01:
    <<: *node-template
    hostname: node01
    depends-on:
      - master

  node02:
    <<: *node-template
    hostname: node02
    depends-on:
      - master


networks:
  cluster-net:
    driver: bridge

volumes:
  cluster-shared:

    # build: .
    # container_name: master
    # hostname: master
    # cpus: 2
    # mem_limit: 2048m
    # volumes:
    #   - cluster-shared:/shared
    # networks:
    #   - cluster-net
    
  # node01:
  #   build: .
  #   container_name: node01
  #   hostname: node01
  #   cpus: 2
  #   mem_limit: 2048m
  #   volumes:
  #     - cluster-shared:/shared
  #   networks:
  #     - cluster-net
  #   depends_on:
  #     - master

